### ISSUE TITLE
Add Hanoi tower function

### ISSUE THREAD

**Issue by arttocode44** [arttocode44/project-learn-prog#7]

**Comment by rardooba** [comment]
La fonction prend trois tours (ou piles) représentées sous forme de chaînes de caractères source, target et aux respectivement, ainsi que le nombre de disques n qui doivent être déplacés de la tour source vers la tour target. La tour aux est utilisée comme tour auxiliaire.

La fonction utilise un algorithme récursif pour résoudre le problème. Si n est égal à 1, le disque peut simplement être déplacé de la tour source vers la tour target. Sinon, la fonction est appelée récursivement pour déplacer les n - 1 disques supérieurs de la tour source à la tour aux, puis le disque inférieur est déplacé de la tour source à la tour target, et enfin les n - 1 disques supérieurs sont déplacés de la tour aux à la tour target.
